# Generated by Django 4.2.1 on 2023-11-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemservice',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
