# Generated by Django 4.2.1 on 2023-11-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_itemservice_name_alter_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
