# Generated by Django 4.2.7 on 2024-09-26 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_transaction_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemservice',
            options={'verbose_name_plural': 'Items & Services'},
        ),
        migrations.AddField(
            model_name='itemservice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='party',
            name='balance_amount',
            field=models.IntegerField(default=0, verbose_name='Balance Amount'),
        ),
        migrations.AlterField(
            model_name='itemservice',
            name='item_type',
            field=models.BooleanField(choices=[(True, 'Item'), (False, 'Service')], default=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='itemservice',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Set to 0 if service'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_no',
            field=models.CharField(max_length=50, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bill_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Bill Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='invoice.party'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoice.itemservice'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Set to 0 if service'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoice.sale'),
        ),
        migrations.CreateModel(
            name='PartyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(default=datetime.date.today, verbose_name='Payment Date')),
                ('amount', models.IntegerField(default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='invoice.party')),
            ],
        ),
    ]
